### ISSUE TITLE
Add helmet security middleware

### ISSUE THREAD

**Issue by wookiecooking** [cohix/Imperium#11]
I recommend some type of middleware for security, maybe even helmet? https://www.npmjs.com/package/helmet

**Comment by cohix** [comment]
I will look into helmet and consider it for the 0.4 release train, thanks for your suggestion!

**Comment by cohix** [comment]
After reading the helmet docs and trying it out, I've decided to reopen this as a feature in the 0.4 release.

**Comment by wookiecooking** [comment]
I am closing this issue, im not sure if you are still maintaining this software, but let me know if you have moved onto a new repo for it as well, I would gladly like to contribute
