### ISSUE TITLE
Needs a License

### ISSUE THREAD

**Issue by devoidfury** [cohix/Imperium#2]
You'll need a license to get anyone to use this, otherwise legal concerns are a huge deal.

I'd recommend some variant of MIT, BSD, or GPL -- but it's entirely up to you as the author.

**Comment by cohix** [comment]
I will add that to the v0_2 branch. Thanks for pointing that out.

**Comment by cohix** [comment]
I put this project on the MIT licence. I've noted that in package.json, and the full licence can be found in Imperium/src/docs/licence.md
